
project_id = "fauoxtziffljgictcvhi"

[functions.send-password-reset]
verify_jwt = false

[functions.send-course-enrollment-confirmation]
verify_jwt = false

[functions.create-auth-account]
verify_jwt = false

[functions.backfill-auth-accounts]
verify_jwt = false
