
project_id = "fauoxtziffljgictcvhi"

[functions.send-password-reset-email]
verify_jwt = false

[functions.reset-password-email]
verify_jwt = false

[functions.confirm-password-reset]
verify_jwt = false

[functions.test-password-reset]
verify_jwt = false

[functions.send-course-enrollment-confirmation]
verify_jwt = false
